server:
  port: 7001

#Eureka配置
eureka:
  instance:
    hostname: eureka7001 #服务端的实例名称

  client:
    register-with-eureka: false # 表示是否向eureka注册中心注册自己
    fetch-registry: false # 如果fetch-registry为false，则表示自己为注册中心
    service-url:  # 监控页面
     #单机： deaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
     #集群(关联其它注册中心)：
        #关联绑定7002和7003端口项目
        defaultZone: http:/localhost:7002/eureka/, http://localhost:7003/eureka/


