server:
  port: 8001
#mybatis配置
mybatis:
  type-aliases-package: com.bear.springcloud.pojo
#  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

#spring配置
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///db01?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT
    username: root
    password: system56

# eureka的配置：服务注册到哪里去
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka/, http://eureka7002:7002/eureka/, http://eureka7003:7003/eureka/ # 注册到7001端口


  instance:
    instance-id: springcloud-provider-dept8001 # 修改eureka默认描述信息

#状态页面的info配置
info:
  app.name: bear-springcloud # 配置名称
  company.name: blog.bearstudy.com  #配置公司信息
